### ISSUE TITLE
Alternative image for day-night cycle

### ISSUE THREAD

**Issue by ostelaymetaule** [MillerMark/MrAnnouncerBot#12]
Hello there!
I watched the last stream and scribbled along the alternative non-licensed(aka free for use) version of the cog day-night cycle image. I saved it as a png but can reexport it into different layers or even make an svg-overhaul if needed. The picture is made in procreate and as such a psd is available too.
Should I create a pull request or is it ok as it is(it should be a transparent png, but i dunno if github actually messes with it)?
Best regards, 
Oste 

![cogdaytime](https://user-images.githubusercontent.com/799935/56691031-30901580-66df-11e9-89cb-ce464fb288b2.png)

**Comment by MillerMark** [comment]
Hi Alex,

Awesome. Thank you so much! I think I can check this in.

- Mark

On Apr 24, 2019, at 2:23 PM, Alexander Elgin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello there!
I watched the last stream and scribbled along the alternative non-licensed version of the cog day-night cycle image. I saved it as a png but can reexport it into different layers or even make an svg-overhaul if needed. The image as made in procreate and I can also send a psd.
Should I create a pull request or is it ok as it is?
Best regards,
Oste

[cogdaytime]<https://user-images.githubusercontent.com/799935/56691031-30901580-66df-11e9-89cb-ce464fb288b2.png>
